[package]
name = "quantum_1d_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "1.7"
# rustc_apfloat = "0.1.3"
num-bigfloat = "1.3.1"
